# Generated by Django 5.0.4 on 2024-05-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childfashion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangsp',
            name='SoLuong',
            field=models.IntegerField(),
        ),
    ]
