# Generated by Django 5.0.4 on 2024-05-18 16:11

import childfashion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childfashion', '0002_alter_bangsp_soluong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangsp',
            name='HinhAnh',
            field=models.ImageField(upload_to=childfashion.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='bangsp',
            name='SoLuong',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
