# Generated by Django 5.0.4 on 2024-05-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childfashion', '0003_alter_bangsp_hinhanh_alter_bangsp_soluong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangsp',
            name='DonGia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
